### ISSUE TITLE
Old yosys commands in makefile (missing -top top key)

### ISSUE THREAD

**Issue by MaxFlatline** [wuxx/icesugar-nano#15]
Hi, found a problem in Blink example. In makefile there is a missing key "-top" for yosys, so build fails.
![Screenshot_1](https://github.com/wuxx/icesugar-nano/assets/83601881/3351dfb1-8b2d-48d9-9c41-104bafc2e307)
![Screenshot_2](https://github.com/wuxx/icesugar-nano/assets/83601881/e397e45c-884b-4fef-99d7-6297b7feed2f)
It's a minor inconvenience, i know, but took me some time to find what's wrong:) Thanks for good work, by the way, your project is awesome!

**Comment by wuxx** [comment]
Hello, okay. Perhaps the latest yosys has updated some parameter configurations, and I will update them. Thank you
