### ISSUE TITLE
Set permanent clock speed.

### ISSUE THREAD

**Issue by TiNredmc** [wuxx/icesugar-nano#4]
Hello, I've been thinking if the on-board APM32 can save last state of clock speed, by utilizing SPI Flash to store the MCO frequency that can later read back. Here's procedure.  

0. Power on.  
1. Keep FPGA under reset by pull CRESET_B low, SPI flash now free to use.
2. Check the last address of Flash whether we already store the Freq configuration (prevent override and First boot friendly after production).
2.1 If There's the configuration, just read and set the MCO output according to that data.
2.2 If not, Write the default 12MHz. to that region. 
3. If user want to change the frequency of the MCO via the command line, put FPGA under reset and write to the last address of Flash to store new frequency and also output that frequency to MCO too.  
4. Release the CRESET_B pin.  

P.S.  
Since the FPGA is working at Fixed Frequency. Reset the FPGA would necessary to reprogram the binary which already changed the timing in the code to match new frequency. So I don't think procedure number 3 is a problem.  
Also the reason to use the very last address on the Flash is because I want to stay away from the FPGA Binary.

**Comment by wuxx** [comment]
hello, will consider it, thanks~!

**Comment by TiNredmc** [comment]
Oh, BTW. The 2MB Flash got plenty of space, that FPGA only require ~32KiB.
