### ISSUE TITLE
opensource iCELink.

### ISSUE THREAD

**Issue by TiNredmc** [wuxx/icesugar-nano#5]
Hi, Did you have any plan to opensource the iCELink of iCESugar nano? Maybe I can use my free time to implement the MCO frequency retention feature to the iCELink.

**Comment by abderraouf-adjal** [comment]
Yes, we need the debugger/programmer firmware source-code to modify the frequencies and fix bugs if the board become unsupported by the developer.

**Comment by TiNredmc** [comment]
> Yes, we need the debugger/programmer firmware source-code to modify the frequencies and fix bugs if the board become unsupported by the developer. 

Actually, I'm currently working on opensource firmware with Drag and drop feature. Really complex FatFS, MSD usb and more. Gonna take a while butbI can't really risk flashing it on the APM32 since I don't have the original formware of that

**Comment by abderraouf-adjal** [comment]
@wuxx 

Hello, after commit [cb6ebf2](https://github.com/wuxx/icesugar-nano/commit/cb6ebf2a894d2e2a3e5e5cc81e42aea160ac69f5) will I assume that the source code of the flashing firmware will be available soon with instructions on how to compile and flash the uploader?

Please note that this is very important for us so we can change the default settings.

**Comment by TiNredmc** [comment]
Hi @abderraouf-adjal I already made the open source version of the iCELink firmware available. Note that There's only Drag N Drop programming feature available, No UART<->iCE40 (Only for iCELink Debug) and MCO frequency fixed at 48MHz (Clock source for iCE40LP1K). [https://github.com/TiNredmc/OpeniCELink](OpeniCELink)

**Comment by abderraouf-adjal** [comment]
That great!

I hope you don't mind this non-related request: Please test this PR for running RISC-V programs from SPI flash in icesugar-nano!
The owner of that repo might accept it if others confirm.

[learn-fpga/pull/66](https://github.com/BrunoLevy/learn-fpga/pull/66)

**Comment by TiNredmc** [comment]
@abderraouf-adjal Have some bad news. I did flashed the code to the APM32 (STM32 Clone used in this board). But It's not working and I can't get the debugger to work (there're many workaround and I tried, non of them work). I want you to stay away from that code until I get it work. Plus, Don't even try to dump the original code. It's read protected....
