### ISSUE TITLE
Can't find iCE FTDI USB device

### ISSUE THREAD

**Issue by pythops** [wuxx/icesugar-nano#6]
I got this error when I try to flash `blink.bin` into the board.

```
$ iceprog blink.bin
init..
Can't find iCE FTDI USB device (vendor_id 0x0403, device_id 0x6010 or 0x6014).
ABORT.
```
I tried `iceprog` with sudo and I got the same result 
I have all the tools mentioned here https://clifford.at/icestorm installed. 

Os: Arch Linux

Do you have any idea on how to solve it ?

Thanks

**Comment by abderraouf-adjal** [comment]
The right tool is `icesprog`, not `iceprog`.

**Comment by pythops** [comment]
Thanks very much :))

**Comment by brandcrz88** [comment]
Hi, I hope someone finds this useful.

I am using Ubuntu, for me the problem had to do with setting the rules and permissions properly.

- Stablish your PATH on your predetermined Shell:

export PATH="/path/to/fomu-toolchain-Linux/bin:$PATH"

- You can see that running "make prog" trows that err, this fixes that:

sudo /path/to/fomu-toolchain-Linux/bin/iceprog stopwatch.bin

- Now make that permanent. Check your device ID with:

lsusb

- If necessary, change your device rules, I had to change my idProduct from 6011 to 6010, and then add a GROUP="dialout".

- Go to:

sudo /etc/udev/rules.d/99-usb-serial.rules

- I changed:

SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6011", MODE="0666"

- To:

SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6010", MODE="0666", GROUP="dialout"

- Reload the rules with:

sudo udevadm control --reload-rules

sudo udevadm trigger

- Add user:

sudo usermod -aG dialout $USER


I hope that now you can run make prog directly from /stopwatch-dual

**Comment by yweihong** [comment]
Yes this is very useful!!  Originally I had to run it with `sudo iceprog top_bitmap.bin`.

But with this I can program without sudo.  I do need to disconnect and reconnect my iCEStick even after the reloading of rules though.

I didn't have a `/etc/udev/rules.d/99-usb-serial.rules` so I created a `/etc/udev/rules.d/50-myusb.rules`

**Comment by yweihong** [comment]
Oh I found out that I don't actually need to create the `50-myusb.rules`.

I can just add the user to `plugdev` group and I can program the iCEStick without sudo. 

As `/lib/udev/rules.d/40-fpga-icestorm.rules` already specified it.
