### ISSUE TITLE
0.96 LCD driver?

### ISSUE THREAD

**Issue by Archfx** [wuxx/icesugar-nano#7]
Could you please share the source files related to the [femtorv_pmod_lcd_0.96](https://github.com/wuxx/icesugar-nano/blob/main/demo/femtorv_pmod_lcd_0.96.bin) demo code?
Thanks

**Comment by wuxx** [comment]
hello, please check it here
https://github.com/wuxx/learn-fpga

**Comment by Archfx** [comment]
Hi Wuxx,

Thanks for the pointer. I already checked here. Does the 0.96 LCD have `SSD1351` driver? Looks like it is a different driver  `(st7735s)` from the datasheet.

Thanks

**Comment by wuxx** [comment]
it's st7735s

**Comment by wuxx** [comment]
ok... it seems that I did'nt commit the driver code. you can also check it here
https://github.com/wuxx/iceZ0mb1e/blob/master/firmware/main/main_st7735.c

**Comment by Archfx** [comment]
Thanks. This helps
